name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key ðŸ”
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 ðŸš€
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            
            # Loyihaga kirish yoki klonlash
            cd ~/telegram-bot || git clone https://github.com/tuxtasinboyev/telegram_bot.git telegram-bot && cd telegram-bot

            echo "ðŸ“¦ Pulling latest changes..."
            git reset --hard
            git pull origin main

            echo "ðŸ“¦ Installing dependencies..."
            npm install

            echo "ðŸ” Restarting with PM2..."
            if pm2 list | grep -q "telegram-bot"; then
              pm2 restart telegram-bot
            else
              pm2 start dist/main.js --name telegram-bot
            fi

            pm2 save

          EOF
