name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key ðŸ”
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add SSH known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 via SSH ðŸš€
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            if [ ! -d "telegram-bot" ]; then
              git clone git@github.com:tuxtasinboyev/telegram_bot.git telegram-bot
            fi
            
            cd telegram-bot

            echo "ðŸ“¦ Pulling latest code..."
            git reset --hard
            git pull origin main

            echo "ðŸ³ Rebuilding and restarting Docker containers..."
            docker compose down
            docker compose up --build -d
          EOF
